### PR TITLE
Ruby enhancements

### PR DESCRIPTION
**Pull request by 3zcurdia**
Small ruby enhancements and changes following ruby style guides

### CODE REVIEW

**Comment by geraldb** [comment]
@3zcurdia  Thanks for your efforts.  I've checked your changes - as far as I can see that's just some reformatting. Sorry if I'm missing something. What are you trying to do?

**Comment by 3zcurdia** [comment]
@geraldb It is just a reformatting, and an easy way to config the gem(gemspec) with a more standard convention. And also you now can run all the test suite with `rake test`

**Comment by geraldb** [comment]
@3zcurdia  Again thanks for your efforts. Sorry to disappoint you I'm not a believer in rubocop and the style conventions. Sorry.  I'm "old school".  About managing gems - the project uses hoe [^1] (it's the industry standard, by the way ;-) and it includes the rake test task too (try rake -T to see all tasks) Again thanks for trying. Keep it up. Cheers.

[1] http://planetruby.github.io/gems/hoe

**Comment by 3zcurdia** [comment]
Ok, @geraldb so keep ruby weird!

**Pull request closed without merging**
